### ISSUE TITLE
undefined method `mysql2_connection' for ActiveRecord::Base:Class

### ISSUE THREAD

**Issue by 0000sir** [dalibor/octoshark#30] opened 2017-08-06 07:59 UTC
Great gem, this is what I'm looking for, thank you!

But I got error message says "undefined method `mysql2_connection' for ActiveRecord::Base:Class" in rails 5.1.2, is this gem updated to latest mysql2 adapter?

or it's because of having sqlite3 and mysql2 database in the same time?

**Comment by 0000sir** [comment] 2017-08-07 14:47
I made myself a simple way to manage connection pools, it works except I don't known about the performance #:-p

```
class PoolManager
  @@pools = {}

  def self.execute_with(endpoint, sql)
    pool = @@pools[endpoint.pathname]
    if pool.nil?
      conf = {endpoint.pathname => {'adapter'=>endpoint.adapter, 'pool'=>endpoint.pool,
          'timeout'=>endpoint.timeout, 'database'=>endpoint.database, 'host'=>endpoint.host,
          'username'=>endpoint.username, 'password'=>endpoint.password}}
      resolver = ActiveRecord::ConnectionAdapters::ConnectionSpecification::Resolver.new(conf)
      spec = resolver.spec(endpoint.pathname.to_sym)
      pool = ActiveRecord::ConnectionAdapters::ConnectionPool.new(spec)
      @@pools[endpoint.pathname] = pool
    end
    pool.with_connection do |conn|
      conn.execute(sql)
    end
  end
end
```

**Comment by dalibor** [comment] 2017-09-26 21:21
@0000sir you're probably using mysql2 adapter in the config. Can you provide a sample app to take a look?

**Comment by dalibor** [comment] 2019-06-24 13:05
Closing this issue. Please re-open with a sample app to reproduce it if the issue is still present.

**Closed by dalibor** 2019-06-24 13:05 UTC
